name: arm_ci_install.yml


on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, reopened, edited, synchronize]

jobs:
  install_arm64:
    runs-on:
      labels: arm-runner-2204
    steps:
      - uses: actions/checkout@v4
        # Existing version
      - name: Install binary(arm64)
        run: |
          ./bor.sh v2.0.2-beta amoy sentry
          ./heimdall.sh v1.2.2 amoy sentry
        # New version
      - name: Install binary and test removal(arm64)
        run: |
          ./bor.sh v2.0.3 amoy sentry
          ./heimdall.sh v1.2.3 amoy sentry