name: x86_ci_install.yml


on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, reopened, edited, synchronize]

jobs:
  install_x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # Existing version
      - name: Install binary(amd64/x86)
        run: |
          ./bor.sh v2.0.4-beta amoy sentry
          ./heimdall.sh v1.2.2 amoy sentry
        # New version
      - name: Install binary and test removal(amd64/x86)
        run: |
          ./bor.sh v2.1.0-beta4 amoy sentry
          ./heimdall.sh v1.2.3 amoy sentry